// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/inspector.proto

package inspector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryType int32

const (
	TelemetryType_TELEMETRY_TYPE_UNSPECIFIED TelemetryType = 0
	TelemetryType_TELEMETRY_TYPE_TRACE       TelemetryType = 1
	TelemetryType_TELEMETRY_TYPE_METRIC      TelemetryType = 2
	TelemetryType_TELEMETRY_TYPE_LOG         TelemetryType = 3
)

// Enum value maps for TelemetryType.
var (
	TelemetryType_name = map[int32]string{
		0: "TELEMETRY_TYPE_UNSPECIFIED",
		1: "TELEMETRY_TYPE_TRACE",
		2: "TELEMETRY_TYPE_METRIC",
		3: "TELEMETRY_TYPE_LOG",
	}
	TelemetryType_value = map[string]int32{
		"TELEMETRY_TYPE_UNSPECIFIED": 0,
		"TELEMETRY_TYPE_TRACE":       1,
		"TELEMETRY_TYPE_METRIC":      2,
		"TELEMETRY_TYPE_LOG":         3,
	}
)

func (x TelemetryType) Enum() *TelemetryType {
	p := new(TelemetryType)
	*p = x
	return p
}

func (x TelemetryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TelemetryType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_inspector_proto_enumTypes[0].Descriptor()
}

func (TelemetryType) Type() protoreflect.EnumType {
	return &file_proto_inspector_proto_enumTypes[0]
}

func (x TelemetryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TelemetryType.Descriptor instead.
func (TelemetryType) EnumDescriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{0}
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Cmd:
	//
	//	*Command_ToggleVerbose
	//	*Command_ToggleOutput
	Cmd           isCommand_Cmd `protobuf_oneof:"cmd"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_inspector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmd() isCommand_Cmd {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *Command) GetToggleVerbose() *ToggleVerbose {
	if x != nil {
		if x, ok := x.Cmd.(*Command_ToggleVerbose); ok {
			return x.ToggleVerbose
		}
	}
	return nil
}

func (x *Command) GetToggleOutput() *ToggleOutput {
	if x != nil {
		if x, ok := x.Cmd.(*Command_ToggleOutput); ok {
			return x.ToggleOutput
		}
	}
	return nil
}

type isCommand_Cmd interface {
	isCommand_Cmd()
}

type Command_ToggleVerbose struct {
	ToggleVerbose *ToggleVerbose `protobuf:"bytes,1,opt,name=toggle_verbose,json=toggleVerbose,proto3,oneof"`
}

type Command_ToggleOutput struct {
	ToggleOutput *ToggleOutput `protobuf:"bytes,2,opt,name=toggle_output,json=toggleOutput,proto3,oneof"`
}

func (*Command_ToggleVerbose) isCommand_Cmd() {}

func (*Command_ToggleOutput) isCommand_Cmd() {}

type ToggleVerbose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleVerbose) Reset() {
	*x = ToggleVerbose{}
	mi := &file_proto_inspector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleVerbose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleVerbose) ProtoMessage() {}

func (x *ToggleVerbose) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleVerbose.ProtoReflect.Descriptor instead.
func (*ToggleVerbose) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{1}
}

type ToggleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleOutput) Reset() {
	*x = ToggleOutput{}
	mi := &file_proto_inspector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleOutput) ProtoMessage() {}

func (x *ToggleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleOutput.ProtoReflect.Descriptor instead.
func (*ToggleOutput) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{2}
}

type TelemetryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type          TelemetryType          `protobuf:"varint,2,opt,name=type,proto3,enum=inspector.TelemetryType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryEvent) Reset() {
	*x = TelemetryEvent{}
	mi := &file_proto_inspector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryEvent) ProtoMessage() {}

func (x *TelemetryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryEvent.ProtoReflect.Descriptor instead.
func (*TelemetryEvent) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryEvent) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TelemetryEvent) GetType() TelemetryType {
	if x != nil {
		return x.Type
	}
	return TelemetryType_TELEMETRY_TYPE_UNSPECIFIED
}

type EmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitResponse) Reset() {
	*x = EmitResponse{}
	mi := &file_proto_inspector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitResponse) ProtoMessage() {}

func (x *EmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitResponse.ProtoReflect.Descriptor instead.
func (*EmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{4}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_inspector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{5}
}

type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TracesObserved  uint64                 `protobuf:"varint,1,opt,name=traces_observed,json=tracesObserved,proto3" json:"traces_observed,omitempty"`
	MetricsObserved uint64                 `protobuf:"varint,2,opt,name=metrics_observed,json=metricsObserved,proto3" json:"metrics_observed,omitempty"`
	LogsObserved    uint64                 `protobuf:"varint,3,opt,name=logs_observed,json=logsObserved,proto3" json:"logs_observed,omitempty"`
	BytesObserved   uint64                 `protobuf:"varint,4,opt,name=bytes_observed,json=bytesObserved,proto3" json:"bytes_observed,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveReaders   int32                  `protobuf:"varint,6,opt,name=active_readers,json=activeReaders,proto3" json:"active_readers,omitempty"`
	ActiveWriters   int32                  `protobuf:"varint,7,opt,name=active_writers,json=activeWriters,proto3" json:"active_writers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_inspector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inspector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_inspector_proto_rawDescGZIP(), []int{6}
}

func (x *StatsResponse) GetTracesObserved() uint64 {
	if x != nil {
		return x.TracesObserved
	}
	return 0
}

func (x *StatsResponse) GetMetricsObserved() uint64 {
	if x != nil {
		return x.MetricsObserved
	}
	return 0
}

func (x *StatsResponse) GetLogsObserved() uint64 {
	if x != nil {
		return x.LogsObserved
	}
	return 0
}

func (x *StatsResponse) GetBytesObserved() uint64 {
	if x != nil {
		return x.BytesObserved
	}
	return 0
}

func (x *StatsResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatsResponse) GetActiveReaders() int32 {
	if x != nil {
		return x.ActiveReaders
	}
	return 0
}

func (x *StatsResponse) GetActiveWriters() int32 {
	if x != nil {
		return x.ActiveWriters
	}
	return 0
}

var File_proto_inspector_proto protoreflect.FileDescriptor

const file_proto_inspector_proto_rawDesc = "" +
	"\n" +
	"\x15proto/inspector.proto\x12\tinspector\"\x93\x01\n" +
	"\aCommand\x12A\n" +
	"\x0etoggle_verbose\x18\x01 \x01(\v2\x18.inspector.ToggleVerboseH\x00R\rtoggleVerbose\x12>\n" +
	"\rtoggle_output\x18\x02 \x01(\v2\x17.inspector.ToggleOutputH\x00R\ftoggleOutputB\x05\n" +
	"\x03cmd\"\x0f\n" +
	"\rToggleVerbose\"\x0e\n" +
	"\fToggleOutput\"R\n" +
	"\x0eTelemetryEvent\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.inspector.TelemetryTypeR\x04type\"\x0e\n" +
	"\fEmitResponse\"\x0e\n" +
	"\fStatsRequest\"\xa4\x02\n" +
	"\rStatsResponse\x12'\n" +
	"\x0ftraces_observed\x18\x01 \x01(\x04R\x0etracesObserved\x12)\n" +
	"\x10metrics_observed\x18\x02 \x01(\x04R\x0fmetricsObserved\x12#\n" +
	"\rlogs_observed\x18\x03 \x01(\x04R\flogsObserved\x12%\n" +
	"\x0ebytes_observed\x18\x04 \x01(\x04R\rbytesObserved\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0eactive_readers\x18\x06 \x01(\x05R\ractiveReaders\x12%\n" +
	"\x0eactive_writers\x18\a \x01(\x05R\ractiveWriters*|\n" +
	"\rTelemetryType\x12\x1e\n" +
	"\x1aTELEMETRY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TELEMETRY_TYPE_TRACE\x10\x01\x12\x19\n" +
	"\x15TELEMETRY_TYPE_METRIC\x10\x02\x12\x16\n" +
	"\x12TELEMETRY_TYPE_LOG\x10\x032\xca\x01\n" +
	"\x10InspectorService\x12;\n" +
	"\x06Stream\x12\x12.inspector.Command\x1a\x19.inspector.TelemetryEvent(\x010\x01\x12:\n" +
	"\x04Emit\x12\x19.inspector.TelemetryEvent\x1a\x17.inspector.EmitResponse\x12=\n" +
	"\bGetStats\x12\x17.inspector.StatsRequest\x1a\x18.inspector.StatsResponseB3Z1github.com/jimschubert/otel-relay/proto/inspectorb\x06proto3"

var (
	file_proto_inspector_proto_rawDescOnce sync.Once
	file_proto_inspector_proto_rawDescData []byte
)

func file_proto_inspector_proto_rawDescGZIP() []byte {
	file_proto_inspector_proto_rawDescOnce.Do(func() {
		file_proto_inspector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inspector_proto_rawDesc), len(file_proto_inspector_proto_rawDesc)))
	})
	return file_proto_inspector_proto_rawDescData
}

var file_proto_inspector_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_inspector_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_inspector_proto_goTypes = []any{
	(TelemetryType)(0),     // 0: inspector.TelemetryType
	(*Command)(nil),        // 1: inspector.Command
	(*ToggleVerbose)(nil),  // 2: inspector.ToggleVerbose
	(*ToggleOutput)(nil),   // 3: inspector.ToggleOutput
	(*TelemetryEvent)(nil), // 4: inspector.TelemetryEvent
	(*EmitResponse)(nil),   // 5: inspector.EmitResponse
	(*StatsRequest)(nil),   // 6: inspector.StatsRequest
	(*StatsResponse)(nil),  // 7: inspector.StatsResponse
}
var file_proto_inspector_proto_depIdxs = []int32{
	2, // 0: inspector.Command.toggle_verbose:type_name -> inspector.ToggleVerbose
	3, // 1: inspector.Command.toggle_output:type_name -> inspector.ToggleOutput
	0, // 2: inspector.TelemetryEvent.type:type_name -> inspector.TelemetryType
	1, // 3: inspector.InspectorService.Stream:input_type -> inspector.Command
	4, // 4: inspector.InspectorService.Emit:input_type -> inspector.TelemetryEvent
	6, // 5: inspector.InspectorService.GetStats:input_type -> inspector.StatsRequest
	4, // 6: inspector.InspectorService.Stream:output_type -> inspector.TelemetryEvent
	5, // 7: inspector.InspectorService.Emit:output_type -> inspector.EmitResponse
	7, // 8: inspector.InspectorService.GetStats:output_type -> inspector.StatsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_inspector_proto_init() }
func file_proto_inspector_proto_init() {
	if File_proto_inspector_proto != nil {
		return
	}
	file_proto_inspector_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_ToggleVerbose)(nil),
		(*Command_ToggleOutput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inspector_proto_rawDesc), len(file_proto_inspector_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inspector_proto_goTypes,
		DependencyIndexes: file_proto_inspector_proto_depIdxs,
		EnumInfos:         file_proto_inspector_proto_enumTypes,
		MessageInfos:      file_proto_inspector_proto_msgTypes,
	}.Build()
	File_proto_inspector_proto = out.File
	file_proto_inspector_proto_goTypes = nil
	file_proto_inspector_proto_depIdxs = nil
}
