// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/inspector.proto

package inspector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InspectorService_Stream_FullMethodName   = "/inspector.InspectorService/Stream"
	InspectorService_Emit_FullMethodName     = "/inspector.InspectorService/Emit"
	InspectorService_GetStats_FullMethodName = "/inspector.InspectorService/GetStats"
)

// InspectorServiceClient is the client API for InspectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InspectorServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, TelemetryEvent], error)
	Emit(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*EmitResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type inspectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInspectorServiceClient(cc grpc.ClientConnInterface) InspectorServiceClient {
	return &inspectorServiceClient{cc}
}

func (c *inspectorServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Command, TelemetryEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InspectorService_ServiceDesc.Streams[0], InspectorService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Command, TelemetryEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InspectorService_StreamClient = grpc.BidiStreamingClient[Command, TelemetryEvent]

func (c *inspectorServiceClient) Emit(ctx context.Context, in *TelemetryEvent, opts ...grpc.CallOption) (*EmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResponse)
	err := c.cc.Invoke(ctx, InspectorService_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, InspectorService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InspectorServiceServer is the server API for InspectorService service.
// All implementations must embed UnimplementedInspectorServiceServer
// for forward compatibility.
type InspectorServiceServer interface {
	Stream(grpc.BidiStreamingServer[Command, TelemetryEvent]) error
	Emit(context.Context, *TelemetryEvent) (*EmitResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedInspectorServiceServer()
}

// UnimplementedInspectorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInspectorServiceServer struct{}

func (UnimplementedInspectorServiceServer) Stream(grpc.BidiStreamingServer[Command, TelemetryEvent]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedInspectorServiceServer) Emit(context.Context, *TelemetryEvent) (*EmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedInspectorServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedInspectorServiceServer) mustEmbedUnimplementedInspectorServiceServer() {}
func (UnimplementedInspectorServiceServer) testEmbeddedByValue()                          {}

// UnsafeInspectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InspectorServiceServer will
// result in compilation errors.
type UnsafeInspectorServiceServer interface {
	mustEmbedUnimplementedInspectorServiceServer()
}

func RegisterInspectorServiceServer(s grpc.ServiceRegistrar, srv InspectorServiceServer) {
	// If the following call panics, it indicates UnimplementedInspectorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InspectorService_ServiceDesc, srv)
}

func _InspectorService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InspectorServiceServer).Stream(&grpc.GenericServerStream[Command, TelemetryEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InspectorService_StreamServer = grpc.BidiStreamingServer[Command, TelemetryEvent]

func _InspectorService_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelemetryEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServiceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InspectorService_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServiceServer).Emit(ctx, req.(*TelemetryEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _InspectorService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InspectorService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InspectorService_ServiceDesc is the grpc.ServiceDesc for InspectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InspectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inspector.InspectorService",
	HandlerType: (*InspectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Emit",
			Handler:    _InspectorService_Emit_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _InspectorService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _InspectorService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/inspector.proto",
}
